name: AHK
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  AHKtoEXE:
    runs-on: windows-latest
    steps:
    - run: /github/Compiler/Ahk2Exe.exe /in /Calculator.ahk /out /Calculator.exe /icon /pad.ico
