name: AHK
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  AHKtoEXE:
    runs-on: windows-latest
    steps:
    - run: |
        cd /a/AHK-Inline-calculator/AHK-Inline-calculator
        dir
