name: AHK
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  AHKtoEXE:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          .\.github\workflows\compiler\AHK2EXE.exe /in ./Calculator.ahk /out ./Calculator.exe /icon pad.ico
      - uses: actions/upload-artifact@v2
        with:
          name: Compiled AHK
          path: ${GITHUB_WORKSPACE}/Calculator.exe
