name: AHK
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  AHKtoEXE:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd %GITHUB_WORKSPACE%
          .\.github\workflows\compiler\AHK2EXE.exe /in ./Calculator.ahk /out ./Calculator.exe /icon pad.ico
